// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCduBf570XfuSnPaLSpgBrjGpnuhyGfVgs',
    appId: '1:290718547533:web:4f3c1562a7bdd291f26604',
    messagingSenderId: '290718547533',
    projectId: 'art-meeting',
    authDomain: 'art-meeting.firebaseapp.com',
    storageBucket: 'art-meeting.appspot.com',
    measurementId: 'G-TS57K5TJ8Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTrruDCDmxmJz2HfSGUWo3OlhJD9A6wJE',
    appId: '1:290718547533:android:4679c57d95b90ed6f26604',
    messagingSenderId: '290718547533',
    projectId: 'art-meeting',
    storageBucket: 'art-meeting.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOwT_voLcgOPIDZp_THsigOYgOhCzNLfI',
    appId: '1:290718547533:ios:70dce21454ed24f0f26604',
    messagingSenderId: '290718547533',
    projectId: 'art-meeting',
    storageBucket: 'art-meeting.appspot.com',
    iosBundleId: 'com.example.makdadApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOwT_voLcgOPIDZp_THsigOYgOhCzNLfI',
    appId: '1:290718547533:ios:524fb7ed46fbb882f26604',
    messagingSenderId: '290718547533',
    projectId: 'art-meeting',
    storageBucket: 'art-meeting.appspot.com',
    iosBundleId: 'com.example.makdadApp.RunnerTests',
  );
}
